name: Splunk Appinspect
on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
  
jobs:
  appinspect-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Download packaging toolkit
        run: wget https://download.splunk.com/misc/packaging-toolkit/splunk-packaging-toolkit-1.0.1.tar.gz
      - name: Install packaging toolkit
        run: pip install splunk-packaging-toolkit-1.0.1.tar.gz
      - name: Package app
        run: |
          slim package -o build/package ${{ inputs.package-name }}
      - name: run Appinspect
        uses: splunk/appinspect-api-action@v3
        with:
          username: ${{ secrets.API_USER }}
          password: ${{ secrets.API_PASS }}
          app_path: build/package
          included_tags: "cloud,self-service,future"
      - name: Collect report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Appinspect-report
          path: AppInspect_response.html
      - name: Collect app package
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: App-package
          path: build/package/
          
